### valid request
POST localhost:3333/signup
Content-Type:application/json

{
  "email": "test@example.com",
  "password": "123456"
}

### invalid email
POST localhost:3333/signup
Content-Type: application/json

{
  "email": "test",
  "password": "123456"
}

### missing email
POST localhost:3333/signup
Content-Type: application/json

{
  "password": "123456"
}
